### PR TITLE
Fancy fetch & template tags

### PR DESCRIPTION
**Pull request by codfish**
@aj-may 

should remove non-fetch code probs, once ios 10.3 is more popular. maybe a month or so

### CODE REVIEW

**Comment by aj-may** [comment]
@codfish can we just add the polyfil instead?

**Comment by codfish** [comment]
yea was gonna do that, but wasn't sure i wanted to go crazy and add external dependencies and ish. you think that would be better?

**Comment by aj-may** [comment]
just grab it from a CDN or some shiz

**Comment by aj-may** [comment]
https://cdnjs.com/libraries/fetch

**Comment by codfish** [comment]
@aj-may updated

**Comment by codfish** [comment]
@aj-may mergeme

**Pull request merged**
